### ISSUE TITLE
isusse: kaf produce don't work

### ISSUE THREAD

**Issue by lihuacai168** [birdayz/kaf#131]
use `kaf produce test_topic` senk message to test_topic
but can't resume the topic from test_topic
![image](https://user-images.githubusercontent.com/11568297/99944569-0ec0ae00-2dae-11eb-97d1-d165845c0029.png)
![image](https://user-images.githubusercontent.com/11568297/99944909-a4f4d400-2dae-11eb-8fed-1b12ad14324c.png)

**Comment by birdayz** [comment]
tbh i never used it interactively. usually you would do it like this:
```
echo -n 'abc' | kaf produce test_topic
```

since you use it interactively, it will not send anything until stdin is closed i think. and ctrl-c will halt the entire application without properly flushing input first. this is not really supported right now, but it could also make sense to read (and send) data per line, if an interactive terminal is connected..

**Comment by lihuacai168** [comment]
> tbh i never used it interactively. usually you would do it like this:
> 
> ```
> echo -n 'abc' | kaf produce test_topic
> ```
> 
> since you use it interactively, it will not send anything until stdin is closed i think. and ctrl-c will halt the entire application without properly flushing input first. this is not really supported right now, but it could also make sense to read (and send) data per line, if an interactive terminal is connected..

thx,it work with `echo -n 'abc' | kaf produce test_topic`.
I've always used Java CLI,so I think that kaf can work interactively.
